# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dinn/projects/bpew

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dinn/projects/bpew

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dinn/projects/bpew/CMakeFiles /home/dinn/projects/bpew//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dinn/projects/bpew/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bpew

# Build rule for target.
bpew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bpew
.PHONY : bpew

# fast build rule for target.
bpew/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/build
.PHONY : bpew/fast

include/imgui/backends/imgui_impl_opengl3.o: include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
include/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.o

include/imgui/backends/imgui_impl_opengl3.i: include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.i

include/imgui/backends/imgui_impl_opengl3.s: include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.s

include/imgui/backends/imgui_impl_sdl2.o: include/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdl2.o

# target to build an object file
include/imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdl2.cpp.o

include/imgui/backends/imgui_impl_sdl2.i: include/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdl2.cpp.i

include/imgui/backends/imgui_impl_sdl2.s: include/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdl2.cpp.s

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

include/imgui/misc/cpp/imgui_stdlib.o: include/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : include/imgui/misc/cpp/imgui_stdlib.o

# target to build an object file
include/imgui/misc/cpp/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : include/imgui/misc/cpp/imgui_stdlib.cpp.o

include/imgui/misc/cpp/imgui_stdlib.i: include/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : include/imgui/misc/cpp/imgui_stdlib.i

# target to preprocess a source file
include/imgui/misc/cpp/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : include/imgui/misc/cpp/imgui_stdlib.cpp.i

include/imgui/misc/cpp/imgui_stdlib.s: include/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : include/imgui/misc/cpp/imgui_stdlib.s

# target to generate assembly for a file
include/imgui/misc/cpp/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : include/imgui/misc/cpp/imgui_stdlib.cpp.s

src/core/file_system.o: src/core/file_system.cpp.o
.PHONY : src/core/file_system.o

# target to build an object file
src/core/file_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/file_system.cpp.o
.PHONY : src/core/file_system.cpp.o

src/core/file_system.i: src/core/file_system.cpp.i
.PHONY : src/core/file_system.i

# target to preprocess a source file
src/core/file_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/file_system.cpp.i
.PHONY : src/core/file_system.cpp.i

src/core/file_system.s: src/core/file_system.cpp.s
.PHONY : src/core/file_system.s

# target to generate assembly for a file
src/core/file_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/file_system.cpp.s
.PHONY : src/core/file_system.cpp.s

src/core/input.o: src/core/input.cpp.o
.PHONY : src/core/input.o

# target to build an object file
src/core/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/input.cpp.o
.PHONY : src/core/input.cpp.o

src/core/input.i: src/core/input.cpp.i
.PHONY : src/core/input.i

# target to preprocess a source file
src/core/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/input.cpp.i
.PHONY : src/core/input.cpp.i

src/core/input.s: src/core/input.cpp.s
.PHONY : src/core/input.s

# target to generate assembly for a file
src/core/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/input.cpp.s
.PHONY : src/core/input.cpp.s

src/core/time.o: src/core/time.cpp.o
.PHONY : src/core/time.o

# target to build an object file
src/core/time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/time.cpp.o
.PHONY : src/core/time.cpp.o

src/core/time.i: src/core/time.cpp.i
.PHONY : src/core/time.i

# target to preprocess a source file
src/core/time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/time.cpp.i
.PHONY : src/core/time.cpp.i

src/core/time.s: src/core/time.cpp.s
.PHONY : src/core/time.s

# target to generate assembly for a file
src/core/time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/time.cpp.s
.PHONY : src/core/time.cpp.s

src/core/window.o: src/core/window.cpp.o
.PHONY : src/core/window.o

# target to build an object file
src/core/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/window.cpp.o
.PHONY : src/core/window.cpp.o

src/core/window.i: src/core/window.cpp.i
.PHONY : src/core/window.i

# target to preprocess a source file
src/core/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/window.cpp.i
.PHONY : src/core/window.cpp.i

src/core/window.s: src/core/window.cpp.s
.PHONY : src/core/window.s

# target to generate assembly for a file
src/core/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/window.cpp.s
.PHONY : src/core/window.cpp.s

src/ecs/scene.o: src/ecs/scene.cpp.o
.PHONY : src/ecs/scene.o

# target to build an object file
src/ecs/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/ecs/scene.cpp.o
.PHONY : src/ecs/scene.cpp.o

src/ecs/scene.i: src/ecs/scene.cpp.i
.PHONY : src/ecs/scene.i

# target to preprocess a source file
src/ecs/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/ecs/scene.cpp.i
.PHONY : src/ecs/scene.cpp.i

src/ecs/scene.s: src/ecs/scene.cpp.s
.PHONY : src/ecs/scene.s

# target to generate assembly for a file
src/ecs/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/ecs/scene.cpp.s
.PHONY : src/ecs/scene.cpp.s

src/editor/editor.o: src/editor/editor.cpp.o
.PHONY : src/editor/editor.o

# target to build an object file
src/editor/editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/editor/editor.cpp.o
.PHONY : src/editor/editor.cpp.o

src/editor/editor.i: src/editor/editor.cpp.i
.PHONY : src/editor/editor.i

# target to preprocess a source file
src/editor/editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/editor/editor.cpp.i
.PHONY : src/editor/editor.cpp.i

src/editor/editor.s: src/editor/editor.cpp.s
.PHONY : src/editor/editor.s

# target to generate assembly for a file
src/editor/editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/editor/editor.cpp.s
.PHONY : src/editor/editor.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/graphics/camera.o: src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.o

# target to build an object file
src/graphics/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.cpp.o

src/graphics/camera.i: src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.i

# target to preprocess a source file
src/graphics/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.cpp.i

src/graphics/camera.s: src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.s

# target to generate assembly for a file
src/graphics/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.cpp.s

src/graphics/framebuffer.o: src/graphics/framebuffer.cpp.o
.PHONY : src/graphics/framebuffer.o

# target to build an object file
src/graphics/framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/framebuffer.cpp.o
.PHONY : src/graphics/framebuffer.cpp.o

src/graphics/framebuffer.i: src/graphics/framebuffer.cpp.i
.PHONY : src/graphics/framebuffer.i

# target to preprocess a source file
src/graphics/framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/framebuffer.cpp.i
.PHONY : src/graphics/framebuffer.cpp.i

src/graphics/framebuffer.s: src/graphics/framebuffer.cpp.s
.PHONY : src/graphics/framebuffer.s

# target to generate assembly for a file
src/graphics/framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/framebuffer.cpp.s
.PHONY : src/graphics/framebuffer.cpp.s

src/graphics/gizmos.o: src/graphics/gizmos.cpp.o
.PHONY : src/graphics/gizmos.o

# target to build an object file
src/graphics/gizmos.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/gizmos.cpp.o
.PHONY : src/graphics/gizmos.cpp.o

src/graphics/gizmos.i: src/graphics/gizmos.cpp.i
.PHONY : src/graphics/gizmos.i

# target to preprocess a source file
src/graphics/gizmos.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/gizmos.cpp.i
.PHONY : src/graphics/gizmos.cpp.i

src/graphics/gizmos.s: src/graphics/gizmos.cpp.s
.PHONY : src/graphics/gizmos.s

# target to generate assembly for a file
src/graphics/gizmos.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/gizmos.cpp.s
.PHONY : src/graphics/gizmos.cpp.s

src/graphics/index_buffer.o: src/graphics/index_buffer.cpp.o
.PHONY : src/graphics/index_buffer.o

# target to build an object file
src/graphics/index_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/index_buffer.cpp.o
.PHONY : src/graphics/index_buffer.cpp.o

src/graphics/index_buffer.i: src/graphics/index_buffer.cpp.i
.PHONY : src/graphics/index_buffer.i

# target to preprocess a source file
src/graphics/index_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/index_buffer.cpp.i
.PHONY : src/graphics/index_buffer.cpp.i

src/graphics/index_buffer.s: src/graphics/index_buffer.cpp.s
.PHONY : src/graphics/index_buffer.s

# target to generate assembly for a file
src/graphics/index_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/index_buffer.cpp.s
.PHONY : src/graphics/index_buffer.cpp.s

src/graphics/model.o: src/graphics/model.cpp.o
.PHONY : src/graphics/model.o

# target to build an object file
src/graphics/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/model.cpp.o
.PHONY : src/graphics/model.cpp.o

src/graphics/model.i: src/graphics/model.cpp.i
.PHONY : src/graphics/model.i

# target to preprocess a source file
src/graphics/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/model.cpp.i
.PHONY : src/graphics/model.cpp.i

src/graphics/model.s: src/graphics/model.cpp.s
.PHONY : src/graphics/model.s

# target to generate assembly for a file
src/graphics/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/model.cpp.s
.PHONY : src/graphics/model.cpp.s

src/graphics/renderer.o: src/graphics/renderer.cpp.o
.PHONY : src/graphics/renderer.o

# target to build an object file
src/graphics/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/renderer.cpp.o
.PHONY : src/graphics/renderer.cpp.o

src/graphics/renderer.i: src/graphics/renderer.cpp.i
.PHONY : src/graphics/renderer.i

# target to preprocess a source file
src/graphics/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/renderer.cpp.i
.PHONY : src/graphics/renderer.cpp.i

src/graphics/renderer.s: src/graphics/renderer.cpp.s
.PHONY : src/graphics/renderer.s

# target to generate assembly for a file
src/graphics/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/renderer.cpp.s
.PHONY : src/graphics/renderer.cpp.s

src/graphics/shader.o: src/graphics/shader.cpp.o
.PHONY : src/graphics/shader.o

# target to build an object file
src/graphics/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shader.cpp.o
.PHONY : src/graphics/shader.cpp.o

src/graphics/shader.i: src/graphics/shader.cpp.i
.PHONY : src/graphics/shader.i

# target to preprocess a source file
src/graphics/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shader.cpp.i
.PHONY : src/graphics/shader.cpp.i

src/graphics/shader.s: src/graphics/shader.cpp.s
.PHONY : src/graphics/shader.s

# target to generate assembly for a file
src/graphics/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shader.cpp.s
.PHONY : src/graphics/shader.cpp.s

src/graphics/texture.o: src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.o

# target to build an object file
src/graphics/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.cpp.o

src/graphics/texture.i: src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.i

# target to preprocess a source file
src/graphics/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.cpp.i

src/graphics/texture.s: src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.s

# target to generate assembly for a file
src/graphics/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.cpp.s

src/graphics/vertex_array.o: src/graphics/vertex_array.cpp.o
.PHONY : src/graphics/vertex_array.o

# target to build an object file
src/graphics/vertex_array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_array.cpp.o
.PHONY : src/graphics/vertex_array.cpp.o

src/graphics/vertex_array.i: src/graphics/vertex_array.cpp.i
.PHONY : src/graphics/vertex_array.i

# target to preprocess a source file
src/graphics/vertex_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_array.cpp.i
.PHONY : src/graphics/vertex_array.cpp.i

src/graphics/vertex_array.s: src/graphics/vertex_array.cpp.s
.PHONY : src/graphics/vertex_array.s

# target to generate assembly for a file
src/graphics/vertex_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_array.cpp.s
.PHONY : src/graphics/vertex_array.cpp.s

src/graphics/vertex_buffer.o: src/graphics/vertex_buffer.cpp.o
.PHONY : src/graphics/vertex_buffer.o

# target to build an object file
src/graphics/vertex_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_buffer.cpp.o
.PHONY : src/graphics/vertex_buffer.cpp.o

src/graphics/vertex_buffer.i: src/graphics/vertex_buffer.cpp.i
.PHONY : src/graphics/vertex_buffer.i

# target to preprocess a source file
src/graphics/vertex_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_buffer.cpp.i
.PHONY : src/graphics/vertex_buffer.cpp.i

src/graphics/vertex_buffer.s: src/graphics/vertex_buffer.cpp.s
.PHONY : src/graphics/vertex_buffer.s

# target to generate assembly for a file
src/graphics/vertex_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_buffer.cpp.s
.PHONY : src/graphics/vertex_buffer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bpew"
	@echo "... include/imgui/backends/imgui_impl_opengl3.o"
	@echo "... include/imgui/backends/imgui_impl_opengl3.i"
	@echo "... include/imgui/backends/imgui_impl_opengl3.s"
	@echo "... include/imgui/backends/imgui_impl_sdl2.o"
	@echo "... include/imgui/backends/imgui_impl_sdl2.i"
	@echo "... include/imgui/backends/imgui_impl_sdl2.s"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... include/imgui/misc/cpp/imgui_stdlib.o"
	@echo "... include/imgui/misc/cpp/imgui_stdlib.i"
	@echo "... include/imgui/misc/cpp/imgui_stdlib.s"
	@echo "... src/core/file_system.o"
	@echo "... src/core/file_system.i"
	@echo "... src/core/file_system.s"
	@echo "... src/core/input.o"
	@echo "... src/core/input.i"
	@echo "... src/core/input.s"
	@echo "... src/core/time.o"
	@echo "... src/core/time.i"
	@echo "... src/core/time.s"
	@echo "... src/core/window.o"
	@echo "... src/core/window.i"
	@echo "... src/core/window.s"
	@echo "... src/ecs/scene.o"
	@echo "... src/ecs/scene.i"
	@echo "... src/ecs/scene.s"
	@echo "... src/editor/editor.o"
	@echo "... src/editor/editor.i"
	@echo "... src/editor/editor.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/graphics/camera.o"
	@echo "... src/graphics/camera.i"
	@echo "... src/graphics/camera.s"
	@echo "... src/graphics/framebuffer.o"
	@echo "... src/graphics/framebuffer.i"
	@echo "... src/graphics/framebuffer.s"
	@echo "... src/graphics/gizmos.o"
	@echo "... src/graphics/gizmos.i"
	@echo "... src/graphics/gizmos.s"
	@echo "... src/graphics/index_buffer.o"
	@echo "... src/graphics/index_buffer.i"
	@echo "... src/graphics/index_buffer.s"
	@echo "... src/graphics/model.o"
	@echo "... src/graphics/model.i"
	@echo "... src/graphics/model.s"
	@echo "... src/graphics/renderer.o"
	@echo "... src/graphics/renderer.i"
	@echo "... src/graphics/renderer.s"
	@echo "... src/graphics/shader.o"
	@echo "... src/graphics/shader.i"
	@echo "... src/graphics/shader.s"
	@echo "... src/graphics/texture.o"
	@echo "... src/graphics/texture.i"
	@echo "... src/graphics/texture.s"
	@echo "... src/graphics/vertex_array.o"
	@echo "... src/graphics/vertex_array.i"
	@echo "... src/graphics/vertex_array.s"
	@echo "... src/graphics/vertex_buffer.o"
	@echo "... src/graphics/vertex_buffer.i"
	@echo "... src/graphics/vertex_buffer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

