# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikolay/Projects/bpew

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikolay/Projects/bpew

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolay/Projects/bpew/CMakeFiles /home/nikolay/Projects/bpew//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolay/Projects/bpew/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bpew

# Build rule for target.
bpew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bpew
.PHONY : bpew

# fast build rule for target.
bpew/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/build
.PHONY : bpew/fast

include/ImGuiFileDialog/ImGuiFileDialog.o: include/ImGuiFileDialog/ImGuiFileDialog.cpp.o
.PHONY : include/ImGuiFileDialog/ImGuiFileDialog.o

# target to build an object file
include/ImGuiFileDialog/ImGuiFileDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuiFileDialog/ImGuiFileDialog.cpp.o
.PHONY : include/ImGuiFileDialog/ImGuiFileDialog.cpp.o

include/ImGuiFileDialog/ImGuiFileDialog.i: include/ImGuiFileDialog/ImGuiFileDialog.cpp.i
.PHONY : include/ImGuiFileDialog/ImGuiFileDialog.i

# target to preprocess a source file
include/ImGuiFileDialog/ImGuiFileDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuiFileDialog/ImGuiFileDialog.cpp.i
.PHONY : include/ImGuiFileDialog/ImGuiFileDialog.cpp.i

include/ImGuiFileDialog/ImGuiFileDialog.s: include/ImGuiFileDialog/ImGuiFileDialog.cpp.s
.PHONY : include/ImGuiFileDialog/ImGuiFileDialog.s

# target to generate assembly for a file
include/ImGuiFileDialog/ImGuiFileDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuiFileDialog/ImGuiFileDialog.cpp.s
.PHONY : include/ImGuiFileDialog/ImGuiFileDialog.cpp.s

include/ImGuizmo/GraphEditor.o: include/ImGuizmo/GraphEditor.cpp.o
.PHONY : include/ImGuizmo/GraphEditor.o

# target to build an object file
include/ImGuizmo/GraphEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/GraphEditor.cpp.o
.PHONY : include/ImGuizmo/GraphEditor.cpp.o

include/ImGuizmo/GraphEditor.i: include/ImGuizmo/GraphEditor.cpp.i
.PHONY : include/ImGuizmo/GraphEditor.i

# target to preprocess a source file
include/ImGuizmo/GraphEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/GraphEditor.cpp.i
.PHONY : include/ImGuizmo/GraphEditor.cpp.i

include/ImGuizmo/GraphEditor.s: include/ImGuizmo/GraphEditor.cpp.s
.PHONY : include/ImGuizmo/GraphEditor.s

# target to generate assembly for a file
include/ImGuizmo/GraphEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/GraphEditor.cpp.s
.PHONY : include/ImGuizmo/GraphEditor.cpp.s

include/ImGuizmo/ImCurveEdit.o: include/ImGuizmo/ImCurveEdit.cpp.o
.PHONY : include/ImGuizmo/ImCurveEdit.o

# target to build an object file
include/ImGuizmo/ImCurveEdit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImCurveEdit.cpp.o
.PHONY : include/ImGuizmo/ImCurveEdit.cpp.o

include/ImGuizmo/ImCurveEdit.i: include/ImGuizmo/ImCurveEdit.cpp.i
.PHONY : include/ImGuizmo/ImCurveEdit.i

# target to preprocess a source file
include/ImGuizmo/ImCurveEdit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImCurveEdit.cpp.i
.PHONY : include/ImGuizmo/ImCurveEdit.cpp.i

include/ImGuizmo/ImCurveEdit.s: include/ImGuizmo/ImCurveEdit.cpp.s
.PHONY : include/ImGuizmo/ImCurveEdit.s

# target to generate assembly for a file
include/ImGuizmo/ImCurveEdit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImCurveEdit.cpp.s
.PHONY : include/ImGuizmo/ImCurveEdit.cpp.s

include/ImGuizmo/ImGradient.o: include/ImGuizmo/ImGradient.cpp.o
.PHONY : include/ImGuizmo/ImGradient.o

# target to build an object file
include/ImGuizmo/ImGradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImGradient.cpp.o
.PHONY : include/ImGuizmo/ImGradient.cpp.o

include/ImGuizmo/ImGradient.i: include/ImGuizmo/ImGradient.cpp.i
.PHONY : include/ImGuizmo/ImGradient.i

# target to preprocess a source file
include/ImGuizmo/ImGradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImGradient.cpp.i
.PHONY : include/ImGuizmo/ImGradient.cpp.i

include/ImGuizmo/ImGradient.s: include/ImGuizmo/ImGradient.cpp.s
.PHONY : include/ImGuizmo/ImGradient.s

# target to generate assembly for a file
include/ImGuizmo/ImGradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImGradient.cpp.s
.PHONY : include/ImGuizmo/ImGradient.cpp.s

include/ImGuizmo/ImGuizmo.o: include/ImGuizmo/ImGuizmo.cpp.o
.PHONY : include/ImGuizmo/ImGuizmo.o

# target to build an object file
include/ImGuizmo/ImGuizmo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImGuizmo.cpp.o
.PHONY : include/ImGuizmo/ImGuizmo.cpp.o

include/ImGuizmo/ImGuizmo.i: include/ImGuizmo/ImGuizmo.cpp.i
.PHONY : include/ImGuizmo/ImGuizmo.i

# target to preprocess a source file
include/ImGuizmo/ImGuizmo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImGuizmo.cpp.i
.PHONY : include/ImGuizmo/ImGuizmo.cpp.i

include/ImGuizmo/ImGuizmo.s: include/ImGuizmo/ImGuizmo.cpp.s
.PHONY : include/ImGuizmo/ImGuizmo.s

# target to generate assembly for a file
include/ImGuizmo/ImGuizmo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImGuizmo.cpp.s
.PHONY : include/ImGuizmo/ImGuizmo.cpp.s

include/ImGuizmo/ImSequencer.o: include/ImGuizmo/ImSequencer.cpp.o
.PHONY : include/ImGuizmo/ImSequencer.o

# target to build an object file
include/ImGuizmo/ImSequencer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImSequencer.cpp.o
.PHONY : include/ImGuizmo/ImSequencer.cpp.o

include/ImGuizmo/ImSequencer.i: include/ImGuizmo/ImSequencer.cpp.i
.PHONY : include/ImGuizmo/ImSequencer.i

# target to preprocess a source file
include/ImGuizmo/ImSequencer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImSequencer.cpp.i
.PHONY : include/ImGuizmo/ImSequencer.cpp.i

include/ImGuizmo/ImSequencer.s: include/ImGuizmo/ImSequencer.cpp.s
.PHONY : include/ImGuizmo/ImSequencer.s

# target to generate assembly for a file
include/ImGuizmo/ImSequencer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/ImGuizmo/ImSequencer.cpp.s
.PHONY : include/ImGuizmo/ImSequencer.cpp.s

include/imgui/backends/imgui_impl_opengl3.o: include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
include/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.o

include/imgui/backends/imgui_impl_opengl3.i: include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.i

include/imgui/backends/imgui_impl_opengl3.s: include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backends/imgui_impl_opengl3.cpp.s

include/imgui/backends/imgui_impl_sdl2.o: include/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdl2.o

# target to build an object file
include/imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdl2.cpp.o

include/imgui/backends/imgui_impl_sdl2.i: include/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdl2.cpp.i

include/imgui/backends/imgui_impl_sdl2.s: include/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdl2.cpp.s

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

include/imgui/misc/cpp/imgui_stdlib.o: include/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : include/imgui/misc/cpp/imgui_stdlib.o

# target to build an object file
include/imgui/misc/cpp/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : include/imgui/misc/cpp/imgui_stdlib.cpp.o

include/imgui/misc/cpp/imgui_stdlib.i: include/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : include/imgui/misc/cpp/imgui_stdlib.i

# target to preprocess a source file
include/imgui/misc/cpp/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : include/imgui/misc/cpp/imgui_stdlib.cpp.i

include/imgui/misc/cpp/imgui_stdlib.s: include/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : include/imgui/misc/cpp/imgui_stdlib.s

# target to generate assembly for a file
include/imgui/misc/cpp/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : include/imgui/misc/cpp/imgui_stdlib.cpp.s

include/imnodes/imnodes.o: include/imnodes/imnodes.cpp.o
.PHONY : include/imnodes/imnodes.o

# target to build an object file
include/imnodes/imnodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imnodes/imnodes.cpp.o
.PHONY : include/imnodes/imnodes.cpp.o

include/imnodes/imnodes.i: include/imnodes/imnodes.cpp.i
.PHONY : include/imnodes/imnodes.i

# target to preprocess a source file
include/imnodes/imnodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imnodes/imnodes.cpp.i
.PHONY : include/imnodes/imnodes.cpp.i

include/imnodes/imnodes.s: include/imnodes/imnodes.cpp.s
.PHONY : include/imnodes/imnodes.s

# target to generate assembly for a file
include/imnodes/imnodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/include/imnodes/imnodes.cpp.s
.PHONY : include/imnodes/imnodes.cpp.s

src/core/input.o: src/core/input.cpp.o
.PHONY : src/core/input.o

# target to build an object file
src/core/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/input.cpp.o
.PHONY : src/core/input.cpp.o

src/core/input.i: src/core/input.cpp.i
.PHONY : src/core/input.i

# target to preprocess a source file
src/core/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/input.cpp.i
.PHONY : src/core/input.cpp.i

src/core/input.s: src/core/input.cpp.s
.PHONY : src/core/input.s

# target to generate assembly for a file
src/core/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/input.cpp.s
.PHONY : src/core/input.cpp.s

src/core/time.o: src/core/time.cpp.o
.PHONY : src/core/time.o

# target to build an object file
src/core/time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/time.cpp.o
.PHONY : src/core/time.cpp.o

src/core/time.i: src/core/time.cpp.i
.PHONY : src/core/time.i

# target to preprocess a source file
src/core/time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/time.cpp.i
.PHONY : src/core/time.cpp.i

src/core/time.s: src/core/time.cpp.s
.PHONY : src/core/time.s

# target to generate assembly for a file
src/core/time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/time.cpp.s
.PHONY : src/core/time.cpp.s

src/core/tokenizer.o: src/core/tokenizer.cpp.o
.PHONY : src/core/tokenizer.o

# target to build an object file
src/core/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/tokenizer.cpp.o
.PHONY : src/core/tokenizer.cpp.o

src/core/tokenizer.i: src/core/tokenizer.cpp.i
.PHONY : src/core/tokenizer.i

# target to preprocess a source file
src/core/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/tokenizer.cpp.i
.PHONY : src/core/tokenizer.cpp.i

src/core/tokenizer.s: src/core/tokenizer.cpp.s
.PHONY : src/core/tokenizer.s

# target to generate assembly for a file
src/core/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/tokenizer.cpp.s
.PHONY : src/core/tokenizer.cpp.s

src/core/window.o: src/core/window.cpp.o
.PHONY : src/core/window.o

# target to build an object file
src/core/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/window.cpp.o
.PHONY : src/core/window.cpp.o

src/core/window.i: src/core/window.cpp.i
.PHONY : src/core/window.i

# target to preprocess a source file
src/core/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/window.cpp.i
.PHONY : src/core/window.cpp.i

src/core/window.s: src/core/window.cpp.s
.PHONY : src/core/window.s

# target to generate assembly for a file
src/core/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/core/window.cpp.s
.PHONY : src/core/window.cpp.s

src/ecs/scene.o: src/ecs/scene.cpp.o
.PHONY : src/ecs/scene.o

# target to build an object file
src/ecs/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/ecs/scene.cpp.o
.PHONY : src/ecs/scene.cpp.o

src/ecs/scene.i: src/ecs/scene.cpp.i
.PHONY : src/ecs/scene.i

# target to preprocess a source file
src/ecs/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/ecs/scene.cpp.i
.PHONY : src/ecs/scene.cpp.i

src/ecs/scene.s: src/ecs/scene.cpp.s
.PHONY : src/ecs/scene.s

# target to generate assembly for a file
src/ecs/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/ecs/scene.cpp.s
.PHONY : src/ecs/scene.cpp.s

src/editor/editor.o: src/editor/editor.cpp.o
.PHONY : src/editor/editor.o

# target to build an object file
src/editor/editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/editor/editor.cpp.o
.PHONY : src/editor/editor.cpp.o

src/editor/editor.i: src/editor/editor.cpp.i
.PHONY : src/editor/editor.i

# target to preprocess a source file
src/editor/editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/editor/editor.cpp.i
.PHONY : src/editor/editor.cpp.i

src/editor/editor.s: src/editor/editor.cpp.s
.PHONY : src/editor/editor.s

# target to generate assembly for a file
src/editor/editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/editor/editor.cpp.s
.PHONY : src/editor/editor.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/graphics/camera.o: src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.o

# target to build an object file
src/graphics/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.cpp.o

src/graphics/camera.i: src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.i

# target to preprocess a source file
src/graphics/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.cpp.i

src/graphics/camera.s: src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.s

# target to generate assembly for a file
src/graphics/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.cpp.s

src/graphics/framebuffer.o: src/graphics/framebuffer.cpp.o
.PHONY : src/graphics/framebuffer.o

# target to build an object file
src/graphics/framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/framebuffer.cpp.o
.PHONY : src/graphics/framebuffer.cpp.o

src/graphics/framebuffer.i: src/graphics/framebuffer.cpp.i
.PHONY : src/graphics/framebuffer.i

# target to preprocess a source file
src/graphics/framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/framebuffer.cpp.i
.PHONY : src/graphics/framebuffer.cpp.i

src/graphics/framebuffer.s: src/graphics/framebuffer.cpp.s
.PHONY : src/graphics/framebuffer.s

# target to generate assembly for a file
src/graphics/framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/framebuffer.cpp.s
.PHONY : src/graphics/framebuffer.cpp.s

src/graphics/gizmos.o: src/graphics/gizmos.cpp.o
.PHONY : src/graphics/gizmos.o

# target to build an object file
src/graphics/gizmos.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/gizmos.cpp.o
.PHONY : src/graphics/gizmos.cpp.o

src/graphics/gizmos.i: src/graphics/gizmos.cpp.i
.PHONY : src/graphics/gizmos.i

# target to preprocess a source file
src/graphics/gizmos.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/gizmos.cpp.i
.PHONY : src/graphics/gizmos.cpp.i

src/graphics/gizmos.s: src/graphics/gizmos.cpp.s
.PHONY : src/graphics/gizmos.s

# target to generate assembly for a file
src/graphics/gizmos.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/gizmos.cpp.s
.PHONY : src/graphics/gizmos.cpp.s

src/graphics/index_buffer.o: src/graphics/index_buffer.cpp.o
.PHONY : src/graphics/index_buffer.o

# target to build an object file
src/graphics/index_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/index_buffer.cpp.o
.PHONY : src/graphics/index_buffer.cpp.o

src/graphics/index_buffer.i: src/graphics/index_buffer.cpp.i
.PHONY : src/graphics/index_buffer.i

# target to preprocess a source file
src/graphics/index_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/index_buffer.cpp.i
.PHONY : src/graphics/index_buffer.cpp.i

src/graphics/index_buffer.s: src/graphics/index_buffer.cpp.s
.PHONY : src/graphics/index_buffer.s

# target to generate assembly for a file
src/graphics/index_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/index_buffer.cpp.s
.PHONY : src/graphics/index_buffer.cpp.s

src/graphics/model.o: src/graphics/model.cpp.o
.PHONY : src/graphics/model.o

# target to build an object file
src/graphics/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/model.cpp.o
.PHONY : src/graphics/model.cpp.o

src/graphics/model.i: src/graphics/model.cpp.i
.PHONY : src/graphics/model.i

# target to preprocess a source file
src/graphics/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/model.cpp.i
.PHONY : src/graphics/model.cpp.i

src/graphics/model.s: src/graphics/model.cpp.s
.PHONY : src/graphics/model.s

# target to generate assembly for a file
src/graphics/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/model.cpp.s
.PHONY : src/graphics/model.cpp.s

src/graphics/renderer.o: src/graphics/renderer.cpp.o
.PHONY : src/graphics/renderer.o

# target to build an object file
src/graphics/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/renderer.cpp.o
.PHONY : src/graphics/renderer.cpp.o

src/graphics/renderer.i: src/graphics/renderer.cpp.i
.PHONY : src/graphics/renderer.i

# target to preprocess a source file
src/graphics/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/renderer.cpp.i
.PHONY : src/graphics/renderer.cpp.i

src/graphics/renderer.s: src/graphics/renderer.cpp.s
.PHONY : src/graphics/renderer.s

# target to generate assembly for a file
src/graphics/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/renderer.cpp.s
.PHONY : src/graphics/renderer.cpp.s

src/graphics/shaders/shader.o: src/graphics/shaders/shader.cpp.o
.PHONY : src/graphics/shaders/shader.o

# target to build an object file
src/graphics/shaders/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader.cpp.o
.PHONY : src/graphics/shaders/shader.cpp.o

src/graphics/shaders/shader.i: src/graphics/shaders/shader.cpp.i
.PHONY : src/graphics/shaders/shader.i

# target to preprocess a source file
src/graphics/shaders/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader.cpp.i
.PHONY : src/graphics/shaders/shader.cpp.i

src/graphics/shaders/shader.s: src/graphics/shaders/shader.cpp.s
.PHONY : src/graphics/shaders/shader.s

# target to generate assembly for a file
src/graphics/shaders/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader.cpp.s
.PHONY : src/graphics/shaders/shader.cpp.s

src/graphics/shaders/shader_builder.o: src/graphics/shaders/shader_builder.cpp.o
.PHONY : src/graphics/shaders/shader_builder.o

# target to build an object file
src/graphics/shaders/shader_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader_builder.cpp.o
.PHONY : src/graphics/shaders/shader_builder.cpp.o

src/graphics/shaders/shader_builder.i: src/graphics/shaders/shader_builder.cpp.i
.PHONY : src/graphics/shaders/shader_builder.i

# target to preprocess a source file
src/graphics/shaders/shader_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader_builder.cpp.i
.PHONY : src/graphics/shaders/shader_builder.cpp.i

src/graphics/shaders/shader_builder.s: src/graphics/shaders/shader_builder.cpp.s
.PHONY : src/graphics/shaders/shader_builder.s

# target to generate assembly for a file
src/graphics/shaders/shader_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader_builder.cpp.s
.PHONY : src/graphics/shaders/shader_builder.cpp.s

src/graphics/shaders/shader_parser.o: src/graphics/shaders/shader_parser.cpp.o
.PHONY : src/graphics/shaders/shader_parser.o

# target to build an object file
src/graphics/shaders/shader_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader_parser.cpp.o
.PHONY : src/graphics/shaders/shader_parser.cpp.o

src/graphics/shaders/shader_parser.i: src/graphics/shaders/shader_parser.cpp.i
.PHONY : src/graphics/shaders/shader_parser.i

# target to preprocess a source file
src/graphics/shaders/shader_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader_parser.cpp.i
.PHONY : src/graphics/shaders/shader_parser.cpp.i

src/graphics/shaders/shader_parser.s: src/graphics/shaders/shader_parser.cpp.s
.PHONY : src/graphics/shaders/shader_parser.s

# target to generate assembly for a file
src/graphics/shaders/shader_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/shaders/shader_parser.cpp.s
.PHONY : src/graphics/shaders/shader_parser.cpp.s

src/graphics/texture.o: src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.o

# target to build an object file
src/graphics/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/texture.cpp.o
.PHONY : src/graphics/texture.cpp.o

src/graphics/texture.i: src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.i

# target to preprocess a source file
src/graphics/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/texture.cpp.i
.PHONY : src/graphics/texture.cpp.i

src/graphics/texture.s: src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.s

# target to generate assembly for a file
src/graphics/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/texture.cpp.s
.PHONY : src/graphics/texture.cpp.s

src/graphics/vertex_array.o: src/graphics/vertex_array.cpp.o
.PHONY : src/graphics/vertex_array.o

# target to build an object file
src/graphics/vertex_array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_array.cpp.o
.PHONY : src/graphics/vertex_array.cpp.o

src/graphics/vertex_array.i: src/graphics/vertex_array.cpp.i
.PHONY : src/graphics/vertex_array.i

# target to preprocess a source file
src/graphics/vertex_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_array.cpp.i
.PHONY : src/graphics/vertex_array.cpp.i

src/graphics/vertex_array.s: src/graphics/vertex_array.cpp.s
.PHONY : src/graphics/vertex_array.s

# target to generate assembly for a file
src/graphics/vertex_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_array.cpp.s
.PHONY : src/graphics/vertex_array.cpp.s

src/graphics/vertex_buffer.o: src/graphics/vertex_buffer.cpp.o
.PHONY : src/graphics/vertex_buffer.o

# target to build an object file
src/graphics/vertex_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_buffer.cpp.o
.PHONY : src/graphics/vertex_buffer.cpp.o

src/graphics/vertex_buffer.i: src/graphics/vertex_buffer.cpp.i
.PHONY : src/graphics/vertex_buffer.i

# target to preprocess a source file
src/graphics/vertex_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_buffer.cpp.i
.PHONY : src/graphics/vertex_buffer.cpp.i

src/graphics/vertex_buffer.s: src/graphics/vertex_buffer.cpp.s
.PHONY : src/graphics/vertex_buffer.s

# target to generate assembly for a file
src/graphics/vertex_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/graphics/vertex_buffer.cpp.s
.PHONY : src/graphics/vertex_buffer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nodes/node.o: src/nodes/node.cpp.o
.PHONY : src/nodes/node.o

# target to build an object file
src/nodes/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/nodes/node.cpp.o
.PHONY : src/nodes/node.cpp.o

src/nodes/node.i: src/nodes/node.cpp.i
.PHONY : src/nodes/node.i

# target to preprocess a source file
src/nodes/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/nodes/node.cpp.i
.PHONY : src/nodes/node.cpp.i

src/nodes/node.s: src/nodes/node.cpp.s
.PHONY : src/nodes/node.s

# target to generate assembly for a file
src/nodes/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/nodes/node.cpp.s
.PHONY : src/nodes/node.cpp.s

src/nodes/node_link.o: src/nodes/node_link.cpp.o
.PHONY : src/nodes/node_link.o

# target to build an object file
src/nodes/node_link.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/nodes/node_link.cpp.o
.PHONY : src/nodes/node_link.cpp.o

src/nodes/node_link.i: src/nodes/node_link.cpp.i
.PHONY : src/nodes/node_link.i

# target to preprocess a source file
src/nodes/node_link.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/nodes/node_link.cpp.i
.PHONY : src/nodes/node_link.cpp.i

src/nodes/node_link.s: src/nodes/node_link.cpp.s
.PHONY : src/nodes/node_link.s

# target to generate assembly for a file
src/nodes/node_link.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bpew.dir/build.make CMakeFiles/bpew.dir/src/nodes/node_link.cpp.s
.PHONY : src/nodes/node_link.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bpew"
	@echo "... include/ImGuiFileDialog/ImGuiFileDialog.o"
	@echo "... include/ImGuiFileDialog/ImGuiFileDialog.i"
	@echo "... include/ImGuiFileDialog/ImGuiFileDialog.s"
	@echo "... include/ImGuizmo/GraphEditor.o"
	@echo "... include/ImGuizmo/GraphEditor.i"
	@echo "... include/ImGuizmo/GraphEditor.s"
	@echo "... include/ImGuizmo/ImCurveEdit.o"
	@echo "... include/ImGuizmo/ImCurveEdit.i"
	@echo "... include/ImGuizmo/ImCurveEdit.s"
	@echo "... include/ImGuizmo/ImGradient.o"
	@echo "... include/ImGuizmo/ImGradient.i"
	@echo "... include/ImGuizmo/ImGradient.s"
	@echo "... include/ImGuizmo/ImGuizmo.o"
	@echo "... include/ImGuizmo/ImGuizmo.i"
	@echo "... include/ImGuizmo/ImGuizmo.s"
	@echo "... include/ImGuizmo/ImSequencer.o"
	@echo "... include/ImGuizmo/ImSequencer.i"
	@echo "... include/ImGuizmo/ImSequencer.s"
	@echo "... include/imgui/backends/imgui_impl_opengl3.o"
	@echo "... include/imgui/backends/imgui_impl_opengl3.i"
	@echo "... include/imgui/backends/imgui_impl_opengl3.s"
	@echo "... include/imgui/backends/imgui_impl_sdl2.o"
	@echo "... include/imgui/backends/imgui_impl_sdl2.i"
	@echo "... include/imgui/backends/imgui_impl_sdl2.s"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... include/imgui/misc/cpp/imgui_stdlib.o"
	@echo "... include/imgui/misc/cpp/imgui_stdlib.i"
	@echo "... include/imgui/misc/cpp/imgui_stdlib.s"
	@echo "... include/imnodes/imnodes.o"
	@echo "... include/imnodes/imnodes.i"
	@echo "... include/imnodes/imnodes.s"
	@echo "... src/core/input.o"
	@echo "... src/core/input.i"
	@echo "... src/core/input.s"
	@echo "... src/core/time.o"
	@echo "... src/core/time.i"
	@echo "... src/core/time.s"
	@echo "... src/core/tokenizer.o"
	@echo "... src/core/tokenizer.i"
	@echo "... src/core/tokenizer.s"
	@echo "... src/core/window.o"
	@echo "... src/core/window.i"
	@echo "... src/core/window.s"
	@echo "... src/ecs/scene.o"
	@echo "... src/ecs/scene.i"
	@echo "... src/ecs/scene.s"
	@echo "... src/editor/editor.o"
	@echo "... src/editor/editor.i"
	@echo "... src/editor/editor.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/graphics/camera.o"
	@echo "... src/graphics/camera.i"
	@echo "... src/graphics/camera.s"
	@echo "... src/graphics/framebuffer.o"
	@echo "... src/graphics/framebuffer.i"
	@echo "... src/graphics/framebuffer.s"
	@echo "... src/graphics/gizmos.o"
	@echo "... src/graphics/gizmos.i"
	@echo "... src/graphics/gizmos.s"
	@echo "... src/graphics/index_buffer.o"
	@echo "... src/graphics/index_buffer.i"
	@echo "... src/graphics/index_buffer.s"
	@echo "... src/graphics/model.o"
	@echo "... src/graphics/model.i"
	@echo "... src/graphics/model.s"
	@echo "... src/graphics/renderer.o"
	@echo "... src/graphics/renderer.i"
	@echo "... src/graphics/renderer.s"
	@echo "... src/graphics/shaders/shader.o"
	@echo "... src/graphics/shaders/shader.i"
	@echo "... src/graphics/shaders/shader.s"
	@echo "... src/graphics/shaders/shader_builder.o"
	@echo "... src/graphics/shaders/shader_builder.i"
	@echo "... src/graphics/shaders/shader_builder.s"
	@echo "... src/graphics/shaders/shader_parser.o"
	@echo "... src/graphics/shaders/shader_parser.i"
	@echo "... src/graphics/shaders/shader_parser.s"
	@echo "... src/graphics/texture.o"
	@echo "... src/graphics/texture.i"
	@echo "... src/graphics/texture.s"
	@echo "... src/graphics/vertex_array.o"
	@echo "... src/graphics/vertex_array.i"
	@echo "... src/graphics/vertex_array.s"
	@echo "... src/graphics/vertex_buffer.o"
	@echo "... src/graphics/vertex_buffer.i"
	@echo "... src/graphics/vertex_buffer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nodes/node.o"
	@echo "... src/nodes/node.i"
	@echo "... src/nodes/node.s"
	@echo "... src/nodes/node_link.o"
	@echo "... src/nodes/node_link.i"
	@echo "... src/nodes/node_link.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

